### ISSUE TITLE
Why Use Kommunicate?

### ISSUE THREAD

**Issue by vikram-s-narayan** [aws-samples/generative-ai-amazon-bedrock-langchain-agent-example#14]
It's not clear why we're using a third party service - Kommunicate when Lex (or the AWS SDK) performs the same function. It would be great if this were clarified in the documentation.

**Comment by kyleblocksom** [comment]
Kommunicate creates a JS snippet that invokes the Lex RecognizeText API with the user provided text input.

You can alternatively use the [Lex WebUI](https://github.com/aws-samples/aws-lex-web-ui), however, I prefer Kommunicate's styling.
