### ISSUE TITLE
the chat not saving into conversation table

### ISSUE THREAD

**Issue by vikmehta-deluxe** [aws-samples/generative-ai-amazon-bedrock-langchain-agent-example#2]
The chat history is not saving into the conversation table.Does it required to upgrade new version? if yes, then which version?

**Comment by kyleblocksom** [comment]
Are you checking the ConversationTable or ConversationIndexTable?

ConversationTable should contain contextual chat history as shown in the attached screenshot.

![ConversationTable](https://github.com/aws-samples/generative-ai-amazon-bedrock-langchain-agent-example/assets/73256380/ff2fe815-f474-40f2-b8fe-5189c95aef2a)

**Comment by vikmehta-deluxe** [comment]
I am referring ConversationTable and chat history is not saving in it.

![DynamoDB Error](https://github.com/aws-samples/generative-ai-amazon-bedrock-langchain-agent-example/assets/131177969/059e8ebf-2e25-408b-b1fe-5aad6fb1c462)

**Comment by kyleblocksom** [comment]
What are your sample prompts and responses?

**Comment by vikmehta-deluxe** [comment]
The chat data is storing into the table after updating the latest code fixes provided for the prompt (issue 1).

However, in many of the chat response we are observing the following prefix text.

- Thought: Do I need to use a tool? No
- Do I need to use a tool? No
- Thought: Do I need to use a tool? Yes Action: FSI Agent Action Input: the data suggested based on agent execution.

What are the changes to make the presentation clean in chat bot?

**Comment by kyleblocksom** [comment]
Sounds like an issue with the instructions you are using to instantiate the Agent in [fsi_agent.py](https://github.com/aws-samples/generative-ai-amazon-bedrock-langchain-agent-example/blob/main/agent/lambda/agent-handler/fsi_agent.py). I would suggest modifying the PREFIX instructions for your Agent.
