### ISSUE TITLE
KendraIndex is not used for RAG

### ISSUE THREAD

**Issue by vikmehta-deluxe** [aws-samples/generative-ai-amazon-bedrock-langchain-agent-example#6]
I am facing following 2 issues when the chatbot is setup from the latest fork repo.

Issue 1: The chat question doesn't use the kendra index as trusted data source at all despite temperature configured to '0.1' 
Issue 2: The chat history is not saving into the table configured under the environment variable "CONVERSATION_TABLE"

It seems the agent execution doesn't invoke tools for running the chain and similarly, doesn't invoke chat for storing the chat.

Appreciate guidance for the fixes.

**Comment by vikas-deluxe** [comment]
no response received for the issue and there are plenty of code change. Hence, It requires re-validation and therefore, I am closing this issue and no action needed.
