### ISSUE TITLE
Message history encryption?

### ISSUE THREAD

**Issue by jplock** [aws-samples/generative-ai-amazon-bedrock-langchain-agent-example#7]
Do you want to demonstrate how to encrypt the message history in DynamoDB in this example?

https://github.com/langchain-ai/langchain/blob/aad3d8bd47d7f5598156ff2bdcc8f736f24a7412/libs/community/langchain_community/chat_message_histories/dynamodb.py#L51

**Comment by kyleblocksom** [comment]
Hi Justin - The DynamoDB table is already encrypting data at-rest as the [SSE specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html) is set to _True_.

For double encryption, you can specify a KMS key ID when calling LangChain's DynamoDBChatMessageHistory method in the agent's [chat class](https://github.com/aws-samples/generative-ai-amazon-bedrock-langchain-agent-example/blob/main/agent/lambda/agent-handler/chat.py).
